#!/bin/sh

# Mount device filesystem.
mount -t devtmpfs devtmpfs /dev

# Mount the /data device into a temporary location so we
# can read the last known boot configuration.
mount -t ext4 /dev/mmcblk0p8 /mnt2

# Check if we should enter debug mode.

# Mount Linux FS
mount -o bind /mnt2/linux /mnt

mount -t proc proc /mnt/proc 
mount -t sysfs sysfs /mnt/sys    

mount -t devtmpfs devtmpfs /mnt/dev
mkdir -p /mnt/dev/pts
mkdir -p /mnt/dev/shm

mount -t devpts devpts /mnt/dev/pts
mount -t tmpfs tmpfs /mnt/dev/shm

umount /dev

# Change roots
exec switch_root /mnt /lib/systemd/systemd

